version: '3.1'

services:
  falcon: &falcon
    build:
      context: .
      dockerfile: ./compose/local/falcon/Dockerfile
    volumes:
    - .:/app
    ports:
    - "9000:9000"
    command: /start.sh

  webpack:
    build:
      context: .
      dockerfile: ./compose/local/webpack/Dockerfile
    depends_on:
    - mongo
    volumes:
    - .:/app
    command: yarn watch
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_admin
      MONGO_INITDB_ROOT_PASSWORD: icansharethis
    volumes:
      - mongo_data_local:/data/db
    ports:
    - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: icansharethis

volumes:
  mongo_data_local: {}